# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoplayergui.ui'
#
# Created: Mon Dec 29 19:47:31 2008
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(578, 301)
        self.pushButtonPrevTrack = QtGui.QPushButton(Dialog)
        self.pushButtonPrevTrack.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.pushButtonPrevTrack.setObjectName("pushButtonPrevTrack")
        self.pushButtonSeekPrev = QtGui.QPushButton(Dialog)
        self.pushButtonSeekPrev.setGeometry(QtCore.QRect(90, 250, 75, 23))
        self.pushButtonSeekPrev.setObjectName("pushButtonSeekPrev")
        self.pushButtonPlay = QtGui.QPushButton(Dialog)
        self.pushButtonPlay.setGeometry(QtCore.QRect(170, 250, 75, 23))
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.pushButtonPause = QtGui.QPushButton(Dialog)
        self.pushButtonPause.setGeometry(QtCore.QRect(250, 250, 75, 23))
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.pushButtonStop = QtGui.QPushButton(Dialog)
        self.pushButtonStop.setGeometry(QtCore.QRect(330, 250, 75, 23))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.pushButtonSeekNext = QtGui.QPushButton(Dialog)
        self.pushButtonSeekNext.setGeometry(QtCore.QRect(410, 250, 75, 23))
        self.pushButtonSeekNext.setObjectName("pushButtonSeekNext")
        self.pushButtonNextTrack = QtGui.QPushButton(Dialog)
        self.pushButtonNextTrack.setGeometry(QtCore.QRect(490, 250, 75, 23))
        self.pushButtonNextTrack.setObjectName("pushButtonNextTrack")
        self.verticalSliderVolume = QtGui.QSlider(Dialog)
        self.verticalSliderVolume.setGeometry(QtCore.QRect(540, 40, 21, 201))
        self.verticalSliderVolume.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderVolume.setObjectName("verticalSliderVolume")
        self.pushButtonAddFile = QtGui.QPushButton(Dialog)
        self.pushButtonAddFile.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.pushButtonAddFile.setObjectName("pushButtonAddFile")
        self.listWidgetPlayList = QtGui.QListWidget(Dialog)
        self.listWidgetPlayList.setGeometry(QtCore.QRect(10, 31, 256, 171))
        self.listWidgetPlayList.setObjectName("listWidgetPlayList")
        self.pushButtonRemoveFile = QtGui.QPushButton(Dialog)
        self.pushButtonRemoveFile.setGeometry(QtCore.QRect(90, 210, 75, 23))
        self.pushButtonRemoveFile.setObjectName("pushButtonRemoveFile")
        self.pushButtonMoveUp = QtGui.QPushButton(Dialog)
        self.pushButtonMoveUp.setGeometry(QtCore.QRect(270, 50, 75, 23))
        self.pushButtonMoveUp.setObjectName("pushButtonMoveUp")
        self.pushButtonMoveDown = QtGui.QPushButton(Dialog)
        self.pushButtonMoveDown.setGeometry(QtCore.QRect(270, 160, 75, 23))
        self.pushButtonMoveDown.setObjectName("pushButtonMoveDown")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 81, 31))
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.checkBoxSecondScreen = QtGui.QCheckBox(Dialog)
        self.checkBoxSecondScreen.setGeometry(QtCore.QRect(180, 210, 111, 21))
        self.checkBoxSecondScreen.setObjectName("checkBoxSecondScreen")
        self.horizontalSliderVideoSize = QtGui.QSlider(Dialog)
        self.horizontalSliderVideoSize.setGeometry(QtCore.QRect(330, 210, 160, 16))
        self.horizontalSliderVideoSize.setMinimum(1)
        self.horizontalSliderVideoSize.setMaximum(2048)
        self.horizontalSliderVideoSize.setSingleStep(1)
        self.horizontalSliderVideoSize.setPageStep(1)
        self.horizontalSliderVideoSize.setProperty("value", QtCore.QVariant(1024))
        self.horizontalSliderVideoSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderVideoSize.setObjectName("horizontalSliderVideoSize")
        self.labelVideoSize = QtGui.QLabel(Dialog)
        self.labelVideoSize.setGeometry(QtCore.QRect(340, 220, 46, 31))
        self.labelVideoSize.setObjectName("labelVideoSize")
        self.checkBoxLockVideoSize = QtGui.QCheckBox(Dialog)
        self.checkBoxLockVideoSize.setGeometry(QtCore.QRect(400, 190, 101, 21))
        self.checkBoxLockVideoSize.setObjectName("checkBoxLockVideoSize")
        self.labelVideoSize_width = QtGui.QLabel(Dialog)
        self.labelVideoSize_width.setGeometry(QtCore.QRect(410, 220, 61, 31))
        self.labelVideoSize_width.setObjectName("labelVideoSize_width")
        self.checkBoxScreenVisible = QtGui.QCheckBox(Dialog)
        self.checkBoxScreenVisible.setGeometry(QtCore.QRect(180, 230, 101, 18))
        self.checkBoxScreenVisible.setObjectName("checkBoxScreenVisible")
        self.checkBoxPlaySingleTrack = QtGui.QCheckBox(Dialog)
        self.checkBoxPlaySingleTrack.setGeometry(QtCore.QRect(270, 80, 101, 19))
        self.checkBoxPlaySingleTrack.setObjectName("checkBoxPlaySingleTrack")
        self.labelNowPlaying = QtGui.QLabel(Dialog)
        self.labelNowPlaying.setGeometry(QtCore.QRect(90, 0, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.labelNowPlaying.setFont(font)
        self.labelNowPlaying.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNowPlaying.setObjectName("labelNowPlaying")
        self.lcdNumberTrackTime = QtGui.QLCDNumber(Dialog)
        self.lcdNumberTrackTime.setGeometry(QtCore.QRect(280, 100, 64, 23))
        self.lcdNumberTrackTime.setObjectName("lcdNumberTrackTime")
        self.lcdNumberRemainingTime = QtGui.QLCDNumber(Dialog)
        self.lcdNumberRemainingTime.setGeometry(QtCore.QRect(280, 130, 64, 23))
        self.lcdNumberRemainingTime.setObjectName("lcdNumberRemainingTime")
        self.horizontalSliderTrackPos = QtGui.QSlider(Dialog)
        self.horizontalSliderTrackPos.setGeometry(QtCore.QRect(10, 280, 551, 16))
        self.horizontalSliderTrackPos.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTrackPos.setObjectName("horizontalSliderTrackPos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Jogi\'s DualScreen VideoPlayer v0.01 ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrevTrack.setText(QtGui.QApplication.translate("Dialog", "< prev. track", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSeekPrev.setText(QtGui.QApplication.translate("Dialog", "<< seek", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPlay.setText(QtGui.QApplication.translate("Dialog", "play >", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPause.setText(QtGui.QApplication.translate("Dialog", "pause ||", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStop.setText(QtGui.QApplication.translate("Dialog", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSeekNext.setText(QtGui.QApplication.translate("Dialog", "seek >>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNextTrack.setText(QtGui.QApplication.translate("Dialog", "next track >>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddFile.setText(QtGui.QApplication.translate("Dialog", "add file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRemoveFile.setText(QtGui.QApplication.translate("Dialog", "remove file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMoveUp.setText(QtGui.QApplication.translate("Dialog", "move up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMoveDown.setText(QtGui.QApplication.translate("Dialog", "move down", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aa0000;\">Playlist</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSecondScreen.setText(QtGui.QApplication.translate("Dialog", "Second Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVideoSize.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><span style=\" color:#000000;\">video size</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLockVideoSize.setText(QtGui.QApplication.translate("Dialog", "lock video size", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVideoSize_width.setText(QtGui.QApplication.translate("Dialog", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxScreenVisible.setText(QtGui.QApplication.translate("Dialog", "Screen Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPlaySingleTrack.setText(QtGui.QApplication.translate("Dialog", "play single track", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNowPlaying.setText(QtGui.QApplication.translate("Dialog", "no track playing", None, QtGui.QApplication.UnicodeUTF8))

